services:
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'

  editor:
    build:
      context: ./editors
      dockerfile: dockerfile.editor
    image: 'editor:latest'

  # db:
  #   image: 'postgres:latest'
  #   ports:
  #     - '5432:5432'
  #   environment:
  #     POSTGRES_DB: mydatabase
  #     POSTGRES_USER: myuser
  #     POSTGRES_PASSWORD: mypassword

